### ISSUE TITLE
I want property vendor lineage (X00P, X00PD)

### ISSUE THREAD

**Issue by Saikatsaha1996** [danascape/android_device_asus_X00P#1]
Please 🙏 help me waiting for your response

With out vendor i can't cook 

Waiting for essential please help

<project path="kernel/X00P" name="[repository]" remote="[remote]" revision="[revision]" />

![Screenshot_2021-12-22-05-37-00-981_tech ula](https://user-images.githubusercontent.com/72664192/147013341-4bde096d-8546-4adb-ad6c-0b9aa808361c.jpg)

**Comment by danascape** [comment]
https://github.com/TheMuppets/proprietary_vendor_asus check for branches

**Comment by Saikatsaha1996** [comment]
> https://github.com/TheMuppets/proprietary_vendor_asus check for branches

Salim brother already done.. thank you
